### ISSUE TITLE
samtools dependency

### ISSUE THREAD

**Issue by tvkent** [mojaveazure/angsd-wrapper#25]
This dependency setup is a bit confusing. I understand not automatically downloading this, but it seems like the wiki is avoiding telling people how to get it.  `brew samtools` comes up with multiple options, and it's unclear if any of these are the most up-to-date version.  The wiki mentions needing to install HSTlib as well, but the samtools download includes this.  The instructions to downloading this are a bit confusing and could probably be more direct. Installing this locally myself was a bit confusing because the samtools site has updated since the last update and it redirects a lot.  Perhaps add a prompt that asks the user if they want it installed and automate it? Or just lay it out clearly in the wiki.

**Comment by mojaveazure** [comment]
Searching for SAMTools in `brew` gives me this:

``` shell
hoffmanp$ brew search samtools
homebrew/science/samtools                homebrew/science/samtools-0.1 
```

If I want to install SAMTools using `brew`:

``` shell
hoffmanp$ brew install samtools
==> Installing samtools from homebrew/science
==> Downloading https://github.com/samtools/samtools/archive/1.2.tar.gz
==> Downloading from https://codeload.github.com/samtools/samtools/tar.gz/1.2
######################################################################## 100.0%
==> make HTSDIR=/usr/local/opt/htslib/include HTSLIB=/usr/local/opt/htslib/lib/l
🍺  /usr/local/Cellar/samtools/1.2: 44 files, 1M, built in 18 seconds
hoffmanp$ samtools

Program: samtools (Tools for alignments in the SAM format)
Version: 1.2 (using htslib 1.2.1)

Usage:   samtools <command> [options]

Commands:
  -- indexing
         faidx       index/extract FASTA
         index       index alignment
  -- editing
         calmd       recalculate MD/NM tags and '=' bases
         fixmate     fix mate information
         reheader    replace BAM header
         rmdup       remove PCR duplicates
         targetcut   cut fosmid regions (for fosmid pool only)
  -- file operations
         bamshuf     shuffle and group alignments by name
         cat         concatenate BAMs
         merge       merge sorted alignments
         mpileup     multi-way pileup
         sort        sort alignment file
         split       splits a file by read group
         bam2fq      converts a BAM to a FASTQ
  -- stats
         bedcov      read depth per BED region
         depth       compute the depth
         flagstat    simple stats
         idxstats    BAM index stats
         phase       phase heterozygotes
         stats       generate stats (former bamcheck)
  -- viewing
         flags       explain BAM flags
         tview       text alignment viewer
         view        SAM<->BAM<->CRAM conversion

```

This version works, which is why I say just use `brew` to install SAMTools. I ran `brew update` right before I did this, so I have the most recent version of `brew` on my Mac.

I say in the tutorial to use `brew install samtools`, as this installs a version of SAMTools that works with ANGSD-wrapper. All Mac commands should work to install ANGSD-wrapper and it's dependencies. I have not included instructions on how to build these packages in a Linux environment, simply because I'm assuming that Linux users know how to install their own software. For those that wish to build SAMTools from source, I point them to the GitHub page, which says "By default, this will build against an HTSlib source tree in `../htslib`. You can alter this to a source tree elsewhere or to a previously-installed HTSlib by configuring with `--with-htslib=DIR`", hence I direct the user to install HTSLib and SAMTools to satisfy this dependency. I re-download HTSLib during the `setup` routine to make sure ANGSD sees a copy of HTSLib; ANGSD looks for HTSLib in `../htslib`, just like SAMTools from source. It does not look for HTSLib in `$PATH`.

Finally, these are available in most package mangers, which I say on the Installation page. At least, it's available in the Ubuntu/Debian repositories and the Fedora/Red Hat repositories.

I don't think adding a routine to install SAMTools is necessary, but if you have any ideas on how to improve the wiki, I am more than open to suggestions!

**Comment by rossibarra** [comment]
I would encourage inclusion of default installation of samtools.  Some
users will not be linux users but using AW on a cluster and not be super
familiar with linuxy stuff.  And the whole point is to make things easy if
possible.

-Jeff

---

Jeffrey Ross-Ibarra

Dept. of Plant Sciences
262 Robbins Hall, Mail Stop 4
University of California
One Shields Ave
Davis, CA 95616

Tel: 530-752-1152
@jrossibarra
www.rilab.org
