### ISSUE TITLE
Shiny - admix plot issue

### ISSUE THREAD

**Issue by ChaochihL** [mojaveazure/angsd-wrapper#4]
## Admix Plot

Currently, Shiny asks users to input `Number of K ancestral populations to graph` as shown:

![shiny_admix](https://cloud.githubusercontent.com/assets/7061412/10873431/380e9096-80da-11e5-94c3-d0dfa2a1154b.png)

The issue is when inputting any number between 1 and 10, there are no visible changes that occur. This may or may not be an issue, but is something to note.

I will try it with different datasets to see if I get the same results.

**Comment by mojaveazure** [comment]
This is likely because each `.qopt` file is specific to one value of K. Look at other `.qopt` files and see if the graph changes. I believe that you won't have to tell Shiny/R which K `.qopt` file we're looking at, based off of the output from ngsAdmix. Look at other `.qopt` files for other Ks and see if the graph changes. If not, try having Shiny read the name of the file to determine what K is and graph accordingly.

**Comment by mojaveazure** [comment]
If I'm right, the only thing K would be useful for is to label the graph with the correct population size. If Shiny can read the names of the files being uploaded to it, this is a simple matter to splitting the name of the string to find what K is. In that case, you could get rid of the box where people say what K is.

**Comment by ChaochihL** [comment]
That's what I suspected and was planning on removing that option. The other `.qopt` files do change the graph.
